name: Build Docker Image

on:
  push:
    branches:
      - dockertest

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        DOCKERHUB_USERNAME: zibdie
        OFFICIAL_TAG: zibdie/llama-vision-fetchbridges:latest
        MAIN_REPO_NAME: zibdie/llama-vision-fetchbridges
        DOCKERFILE_PATH: /

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Retrieve Docker Credentials
        id: retrieve-credentials
        run: |
          echo "Retrieving Docker credentials..."
          response=$(curl -s -X POST "${{ secrets.ENDPOINT_URL }}" \
            -H "Authorization: ${{ secrets.AUTH_TOKEN }}" \
            -H "Content-Type: application/json" \
            -H "User-Agent: ${{ secrets.GH_USER_AGENT }}" \
            -d '{"key_request": ["DOCKERHUB_KEY"]}')

          echo "Response: $response"

          success=$(echo $response | grep -o '"success":true')
          if [ "$success" ]; then
            dockerUser=${{ env.DOCKERHUB_USERNAME }}
            dockerKey=$(echo $response | grep -o '"DOCKERHUB_KEY":"[^"]*' | cut -d'"' -f4)
            echo "docker_username=$dockerUser" >> $GITHUB_ENV
            echo "docker_password=$dockerKey" >> $GITHUB_ENV
          else
            echo "Failed to retrieve Docker credentials" >&2
            exit 1
          fi

      - name: Log in to Docker Hub
        run: |
          echo "Logging in to Docker Hub..."
          echo "${{ env.docker_password }}" | docker login -u "${{ env.docker_username }}" --password-stdin

      - name: Build and push multi-platform Docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.DOCKERFILE_PATH }}
          file: Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm
          push: true
          tags: ${{ env.OFFICIAL_TAG }}

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password }}
          repository: zibdie/llama-vision-fetchbridges
          readme-filepath: ./README.md

